'use client';

import React, { useEffect, useState } from 'react';

export default function OnboardingFlow() {
    const [isVisible, setIsVisible] = useState(false);
    const [currentStep, setCurrentStep] = useState(0);

    useEffect(() => {
        // Check if user has seen onboarding
        const hasSeenOnboarding = localStorage.getItem('polymarket-times-onboarding');
        if (!hasSeenOnboarding) {
            // Delay showing onboarding by 1 second so page loads first
            setTimeout(() => {
                setIsVisible(true);
            }, 1000);
        }
    }, []);

    const handleClose = () => {
        setIsVisible(false);
        localStorage.setItem('polymarket-times-onboarding', 'true');
    };

    const handleNext = () => {
        if (currentStep < steps.length - 1) {
            setCurrentStep(currentStep + 1);
        } else {
            handleClose();
        }
    };

    const handlePrev = () => {
        if (currentStep > 0) {
            setCurrentStep(currentStep - 1);
        }
    };

    const steps = [
        {
            title: "Welcome to The Polymarket Times",
            content: (
                <div>
                    <p className="font-serif text-sm mb-4">
                        A Victorian-era newspaper chronicling the modern world of prediction markets.
                        Our mechanical scribes transform raw market data into editorial intelligence.
                    </p>
                    <p className="font-serif text-sm">
                        Every story you read is automatically generated by our AI agents,
                        who analyze thousands of markets to bring you the most significant developments.
                    </p>
                </div>
            ),
        },
        {
            title: "Understanding Market Odds",
            content: (
                <div>
                    <p className="font-serif text-sm mb-4">
                        Each story displays odds in cents (¢), representing the market's confidence:
                    </p>
                    <div className="space-y-3 mb-4">
                        <div className="border border-black p-3 bg-green-50">
                            <div className="font-bold text-xs mb-1">75¢ = 75% probability</div>
                            <div className="text-xs font-serif">High confidence this event will occur</div>
                        </div>
                        <div className="border border-black p-3 bg-yellow-50">
                            <div className="font-bold text-xs mb-1">50¢ = 50% probability</div>
                            <div className="text-xs font-serif">Highly contested market</div>
                        </div>
                        <div className="border border-black p-3 bg-red-50">
                            <div className="font-bold text-xs mb-1">25¢ = 25% probability</div>
                            <div className="text-xs font-serif">Market thinks this is unlikely</div>
                        </div>
                    </div>
                    <p className="font-serif text-sm italic">
                        These are real markets where people wager real money on their predictions.
                    </p>
                </div>
            ),
        },
        {
            title: "Navigating The Times",
            content: (
                <div>
                    <p className="font-serif text-sm mb-4">
                        The newspaper is organized like a traditional broadsheet:
                    </p>
                    <ul className="space-y-2 text-sm font-serif list-none">
                        <li className="flex gap-2">
                            <span className="font-bold">📰</span>
                            <span><strong>Lead Story:</strong> The most significant market development</span>
                        </li>
                        <li className="flex gap-2">
                            <span className="font-bold">📋</span>
                            <span><strong>Market Briefs:</strong> Quick updates on trending markets</span>
                        </li>
                        <li className="flex gap-2">
                            <span className="font-bold">🏛️</span>
                            <span><strong>Fed Reserve Widget:</strong> Consensus on interest rates</span>
                        </li>
                        <li className="flex gap-2">
                            <span className="font-bold">✉️</span>
                            <span><strong>Daily Dispatch:</strong> Subscribe for morning editions</span>
                        </li>
                    </ul>
                    <p className="font-serif text-sm mt-4 italic">
                        Click any story to view the full market on Polymarket.
                    </p>
                </div>
            ),
        },
        {
            title: "Accessibility Features",
            content: (
                <div>
                    <p className="font-serif text-sm mb-4">
                        We've built features to enhance your reading experience:
                    </p>
                    <div className="space-y-3">
                        <div className="border border-black p-3">
                            <div className="font-bold text-xs mb-1">👓 Readable Mode</div>
                            <div className="text-xs font-serif">
                                Click the floating button (bottom-right) to increase font sizes and improve contrast
                            </div>
                        </div>
                        <div className="border border-black p-3">
                            <div className="font-bold text-xs mb-1">📱 Mobile-Friendly</div>
                            <div className="text-xs font-serif">
                                Tap "View Market Briefs" to access sidebar content on mobile devices
                            </div>
                        </div>
                        <div className="border border-black p-3">
                            <div className="font-bold text-xs mb-1">⚡ Live Updates</div>
                            <div className="text-xs font-serif">
                                Editions refresh every 4 hours with the latest market intelligence
                            </div>
                        </div>
                    </div>
                </div>
            ),
        },
    ];

    if (!isVisible) return null;

    return (
        <>
            {/* Backdrop */}
            <div
                className="fixed inset-0 bg-black/70 z-[60] animate-fade-in"
                onClick={handleClose}
            />

            {/* Modal */}
            <div className="fixed inset-0 z-[70] flex items-center justify-center p-4 pointer-events-none">
                <div
                    className="bg-[#f4f1ea] border-4 border-double border-black max-w-2xl w-full max-h-[90vh] overflow-y-auto pointer-events-auto animate-success-reveal"
                    onClick={(e) => e.stopPropagation()}
                >
                    {/* Header */}
                    <div className="border-b-2 border-black p-6 bg-[#e6e2d8]">
                        <div className="flex items-start justify-between">
                            <div>
                                <h2 className="font-blackletter text-3xl mb-1">
                                    {steps[currentStep].title}
                                </h2>
                                <div className="text-xs uppercase tracking-widest font-bold">
                                    Step {currentStep + 1} of {steps.length}
                                </div>
                            </div>
                            <button
                                onClick={handleClose}
                                className="text-2xl hover:bg-black hover:text-white w-8 h-8 flex items-center justify-center border border-black transition"
                                aria-label="Close onboarding"
                            >
                                ×
                            </button>
                        </div>
                    </div>

                    {/* Content */}
                    <div className="p-6">
                        {steps[currentStep].content}
                    </div>

                    {/* Footer */}
                    <div className="border-t-2 border-black p-6 bg-[#e6e2d8] flex items-center justify-between">
                        <button
                            onClick={handlePrev}
                            disabled={currentStep === 0}
                            className="px-4 py-2 border border-black text-xs uppercase font-bold hover:bg-black hover:text-white transition disabled:opacity-30 disabled:cursor-not-allowed disabled:hover:bg-transparent disabled:hover:text-black"
                        >
                            Previous
                        </button>

                        {/* Progress dots */}
                        <div className="flex gap-2">
                            {steps.map((_, idx) => (
                                <div
                                    key={idx}
                                    className={`w-2 h-2 rounded-full border border-black ${
                                        idx === currentStep ? 'bg-black' : 'bg-transparent'
                                    }`}
                                />
                            ))}
                        </div>

                        <button
                            onClick={handleNext}
                            className="px-4 py-2 bg-black text-white text-xs uppercase font-bold hover:bg-gray-800 transition"
                        >
                            {currentStep === steps.length - 1 ? 'Start Reading' : 'Next'}
                        </button>
                    </div>
                </div>
            </div>
        </>
    );
}
